### ISSUE TITLE
Doughnut Chart empty

### ISSUE THREAD

**Issue by stephan10** [githiro/drawDoughnutChart#1]
If you have only one value in the Doughnut Chart and turn animation off then the doughnut chart will actually be empty.

here is an example http://codepen.io/anon/pen/mdyBv

**Comment by stephan10** [comment]
has anyone manage to look into this or found a fix?

**Comment by stephan10** [comment]
ok I have found a way around the problem but not sure it is the best to do it.

http://codepen.io/anon/pen/kEjtB

changes are at line 179 - 182

**Comment by githiro** [comment]
@stephan10 Thanks for your report;)
I also found another rendering issue with animation on this case, so I decided to draw "Hollow circle" when we have only one value in the Doughnut Chart(with and without animation).
Have a look at this and let me know if this also works for you.

http://codepen.io/githiro/pen/niEcH

Changes are at line 131 - 155, 181 - 186

**Comment by stephan10** [comment]
Yes seems to be working nicely.

On 8 May 2014 15:10, githiro notifications@github.com wrote:

> @stephan10 https://github.com/stephan10 Thanks for your report;)
> I also found another rendering issue with animation on this case, so I
> decided to draw "Hollow circle" when we have only one value in the Doughnut
> Chart(with and without animation).
> Have a look at this and let me know if this also works for you.
> 
> http://codepen.io/githiro/pen/niEcH
> 
> Changes are at line 131 - 154, 180 - 185
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/githiro/drawDoughnutChart/issues/1#issuecomment-42554146
> .

## 

## 

_Stephan Gerlach_Web Developer
First 10 Digital
Rose Wharf
Rose House - Riverside Suite
East Street
Leeds
LS9 8EE

+44 (0) 1132 445 273

stephan@first10.co.uk
www.first10.co.uk
@first10digital

DISCLAIMER: This email and any attachments to it may be confidential and
are intended solely for the use of the individual to whom it is addressed.
Any views or opinions expressed are solely those of the author and do not
necessarily represent those of First 10 Digital Ltd. If you are not the
intended recipient of this email, you must neither take any action based
upon its contents, nor copy or show it to anyone. Please contact the sender
if you believe you have received this email in error. Please check
any attached proofs carefully as First 10 Digital Ltd cannot accept
any responsibility or liability for any errors or omissions on client
proofs. Copyright: Any intellectual property sent by email remains the
sole property of First 10 Digital Ltd. Registered in England and
Wales. Registered Address Waterloo Court, 17 Hunslet Road, Leeds, LS10
1QN  Company No. 07186597. VAT No. GB 988 212781

**Comment by githiro** [comment]
Solved.
